### ISSUE TITLE
Apkcombo's xapk support

### ISSUE THREAD

**Issue by KarmaMod** [kikfox/kikfox#7]
Can you add xapk support downloaded from Apkcombo? getting this error trying to decompile xapk 

`AndrolibException: No such file or directory:`

Link: https://apkcombo.com/apk-downloader/?package=com.roblox.client&device=default&arches=default&sdkInt=default&format=apk&dpi=480&lang=en

I know it has single APK, but i use it as an example

**Comment by kikfox** [comment]
To decompile xapk:
1- Extract the xapk file to some directory
2- Input the extracted directory 
E.g 
java  -jar kikfox.jar "path/to/directory"

**Comment by KarmaMod** [comment]
@kikfox did that, but getting an error `AndrolibException: 'base.apk' file doesn't exist in the directory! 'E:\Downloads\xapk'`. I must rename it manually to base.apk in order to decompile. Can you make it auto detecting base apk, and maybe support xapk file without having to extract it?
